# Generated by Django 3.2.6 on 2021-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_panel', '0002_activities_events_milestones_phd_placements_projects_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
