# Generated by Django 3.2.6 on 2021-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='semester',
            field=models.CharField(default='Odd', max_length=5),
            preserve_default=False,
        ),
    ]
